CREATE TABLE AUTHORS (
  ID    BIGINT NOT NULL,
  BIO   VARCHAR(255),
  NAME  VARCHAR(255),
  PRIMARY KEY(ID)
);

CREATE TABLE AUTHORS_COURSES (
  AUTHOR_ID BIGINT NOT NULL,
  COURSE_ID BIGINT NOT NULL,
  PRIMARY KEY(AUTHOR_ID, COURSE_ID)
);

CREATE TABLE COURSES (
  ID    BIGINT,
  NAME  VARCHAR(255) NOT NULL,
  CATEGORY  VARCHAR(255) NOT NULL,
  RATING    INT NOT NULL,
  DESCRIPTION   VARCHAR(255) NOT NULL,
  PRIMARY KEY(ID)
);

-- authors_courses 테이블에 있는 course_id 컬럼이 courses 테이블의 id 컬럼을 참조하는 외래 키를 생성
ALTER TABLE AUTHORS_COURSES
  ADD CONSTRAINT COURSE_ID_FK FOREIGN KEY (COURSE_ID)
  REFERENCES COURSES (ID);

-- authors_courses 테이블에 있는 author_id 컬럼이 authors 테이블의 id 컬럼을 참조하는 외래 키를 생성
ALTER TABLE AUTHORS_COURSES
  ADD CONSTRAINT AUTHOR_ID_FK FOREIGN KEY (AUTHOR_ID)
  REFERENCES AUTHORS (ID);