CREATE TABLE COURSES(
    id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(20) NOT NULL,
    rating INT NOT NULL,
    description VARCHAR(1000) NOT NULL,
    PRIMARY KEY (id)
);