DROP TABLE IF EXISTS COURSES;

CREATE TABLE COURSES (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  CATEGORY VARCHAR(255) NOT NULL,
  RATING INT NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL
);